name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
      - run: yarn install
      - run: |
          yarn build:cli
          yarn build:sqs
          yarn build:dynamodb
      - run: |
          yarn publish:cli --access=public --new-version=${{ github.event.release.tag_name }}
          yarn publish:sqs --access=public --new-version=${{ github.event.release.tag_name }}
          yarn publish:dynamodb --access=public --new-version=${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
